loki:  
  schemaConfig:
    configs:
    - from: "2020-09-07"
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: loki_index_
        period: 24h


  storageConfig:
    aws:
      s3: s3://lon1.digitaloceanspaces.com/junkyard
      access_key_id: DO00EBGABCWEYVFXRUTG
      secret_access_key: X1jodLUuMctQobt3UITVvKEmktMAAWSbwSeqSUsubDM
    boltdb_shipper:
      shared_store: s3
      active_index_directory: /var/loki/index
      cache_location: /var/loki/cache
    filesystem:
      directory: /var/loki/chunks
