grafana:  
  persistence:
     enabled: true
     storageClassName: do-block-storage
     accessModes:
       - ReadWriteOnce
     size: 5Gi



prometheus:  
  prometheusSpec:    
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: do-block-storage
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi